name: poker
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - attrs==25.3.0
      - bidict
      - blinker
      - bootstrapped==0.0.2
      - certifi==2025.4.26
      - cffi
      - charset-normalizer==3.4.2
      - click
      - colorama
      - contourpy
      - cryptography
      - cycler
      - dnspython
      - eventlet
      - Flask
      - Flask-SocketIO
      - fonttools
      - greenlet
      - h11
      - idna==3.10
      - importlib_metadata
      - itsdangerous
      - Jinja2
      - joblib==1.5.1
      - kiwisolver
      - MarkupSafe
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - munkres==1.1.4
      - numpy
      - packaging
      - pandas==2.2.3
      - parameterized==0.9.0
      - patsy==1.0.1
      - pillow
      - pipfile==0.0.2
      - pybloom_live==4.0.0
      - pycparser
      - pygame==2.6.1
      - pylsl==1.17.6
      - pyOpenSSL
      - pyparsing
      - pyqtgraph==0.9.10
      - PySide6==6.7.2
      - python-dateutil
      - python-engineio
      - python-socketio
      - pytz==2025.2
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy
      - shiboken6==6.7.2
      - simple-websocket
      - six
      - sniffio
      - statsmodels==0.14.4
      - sympy==1.14.0
      - tealang==0.4.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tornado
      - typing_extensions
      - tzdata==2025.2
      - unicodedata2
      - urllib3==2.4.0
      - Werkzeug
      - wsproto
      - xxhash==3.5.0
      - z3-solver==4.15.0.0
      - zipp
      - tqdm
      - pyserial
